name: chat_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.9
  - pip

  - pip:
      - annotated-types==0.7.0
      - build==1.2.1
      - cachecontrol==0.14.0
      - cachetools==5.5.0
      - cleo==2.1.0
      - click==8.1.7
      - crashtest==0.4.1
      - distlib==0.3.8
      - dnspython==2.6.1
      - dulwich==0.21.7
      - email-validator==2.2.0
      - fastapi==0.112.1
      - fastapi-cli==0.0.5
      - filelock==3.15.4
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.1
      - google-api-python-client==2.142.0
      - google-auth==2.34.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.63.2
      - grpcio==1.66.0
      - grpcio-status==1.62.3
      - httplib2==0.22.0
      - httptools==0.6.1
      - installer==0.7.0
      - jaraco-classes==3.4.0
      - keyring==24.3.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - more-itertools==10.4.0
      - msgpack==1.0.8
      - ollama==0.3.1
      - pandocfilters==1.5.1
      - pillow==10.4.0
      - pkginfo==1.11.1
      - poetry==1.8.3
      - poetry-core==1.9.0
      - poetry-plugin-export==1.8.0
      - proto-plus==1.24.0
      - protobuf==4.25.4
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - rapidfuzz==3.9.6
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rsa==4.9
      - shellingham==1.5.4
      - soupsieve==2.6
      - starlette==0.38.2
      - tomlkit==0.13.2
      - tqdm==4.66.5
      - trove-classifiers==2024.7.2
      - typer==0.12.4
      - uritemplate==4.1.1
      - uvicorn==0.30.6
      - virtualenv==20.26.3
      - watchfiles==0.23.0
      - websockets==13.0
